window.credential = {
    constants: {
        credentialHoldersEntity: 'credentialholders'
    },
    events: {
        treeview_item_selected: 'treeviewitemselected',
        credential_holder_list_refresh: 'credentialholderlistrefresh',
        show_manage_credential: 'showmanagecredential',
        cancel_manage_credential: 'hidemanagecredential',
        credential_saved: 'credentialsaved',
        show_manage_credential_holder: 'showmanagecredentialholder',
        cancel_manage_credential_holder: 'hidemanagecredentialholder',
        credential_holder_saved: 'credentialholdersaved',
        credential_holder_deleted: 'credentialholderdeleted',
        credential_holder_confirm_delete: 'credentialholderconfirmdelete',
        credential_holder_delete_confirmed: 'credentialholderdeleteconfirmed',
        credential_file_upload_failed: 'credentialfileuploadfailed',
        credential_holder_associate: 'credentialholderassociate',
        cancel_manage_unassigned_credentials: 'hidemanageunassignedcredentials',
        credential_holder_associate: 'credentialholderassociate',
        credential_count_refresh: 'credentialcountrefresh',
        show_unassigned_credentials: 'showunassignedcredentials',
        hide_unassigned_credentials: 'hideunassignedcredentials',
        credential_deleted: 'credentialdeleted',
        credential_confirm_delete: 'credentialconfirmdelete',
        credential_delete_confirmed: 'credentialdeleteconfirmed',
        show_assigned_credentials: 'showassignedcredentials',
        hide_assigned_credentials: 'hideassignedcredentials',
        credential_confirm_dissociate: 'credentialconfirmdissociate',
        credential_dissociate_confirmed: 'credentialdissociateconfirmed',
        credential_dissociated: 'credentialdissociated',
        show_manage_credential_options: 'showmanagecredentialoptions',
        hide_manage_credential_options: 'hidemanagecredentialoptions',
        hide_credential: 'hidecredential',
        credential_list_refresh: 'credentiallistrefresh',
        hide_delete_credential_holder_cofirm: 'hidedeletecredentialholdercofirm',
        show_delete_credential_holder_cofirm: 'showdeletecredentialholdercofirm'
    },
    messages: {
        credential_save_success: Resources.Credential_Save_Success,
        credential_save_failed: Resources.Credential_Save_Failed,
        credential_holder_save_success: Resources.Credential_Holder_Save_Success,
        credential_holder_save_failed: Resources.Credential_Holder_Save_Failed,
        credential_holder_delete_confirm: Resources.Credential_Holder_Delete_Confirm,
        credential_holder_delete_success: Resources.Credential_Holder_Delete_Success,
        credential_holder_delete_fail: Resources.Credential_Holder_Delete_Failed,
        credential_holder_delete_fail_no_permission: Resources.Credential_Holder_Delete_Failed_Authorization_Failed,
        credential_holder_delete_norecord: Resources.Credential_Holder_Delete_No_Record,
        file_extension_mismatch: Resources.Credential_File_Extension_Mismatch,
        file_size_exceeds: Resources.Credential_File_Size_Exceeds,
        credential_delete_confirm: Resources.Credential_Delete_Confirm,
        credential_delete_success: Resources.Credential_Delete_Success,
        credential_delete_fail: Resources.Credential_Delete_Failed,
        credential_delete_norecord: Resources.Credential_Delete_No_Record,
        credential_dissociate_confirm: Resources.Credential_Dissociate_Confirm,
        credential_dissociate_success: Resources.Credential_Dissociate_Success,
        credential_dissociate_fail: Resources.Credential_Dissociate_Failed,
        credential_dissociate_norecord: Resources.Credential_Dissociate_No_Record,
        authorization_failed: Resources.FRAMEWORK_AUTHORIZATION_FAILED,
        error_on_server: Resources.Server_Error
    },
    credentialCredentialHolderRelationEnum:  {
        None            : 0,
        Associated      : 1,
        TobeAssociated  : 2,
        TobeDissociated : 3,
        TobeDeleted     : 4
    }
};